### PR TITLE
Fixed scaling in the ratchet and clank irb plugin

### PR DESCRIPTION
**Pull request by NefariousTechSupport**
Ties from the ratchet and clank games were squished weirdly but i fixed it

### CODE REVIEW

**Comment by Dinoguy1000** [comment]
Currently the file diff is unusable; dropping the original and modified versions into an external diff checker shows you making random whitespace changes on top of your other changes. I'd suggest to remove the whitespace changes and see if that produces a usable diff here; as is, I can't see this getting merged, simply because of how much extra effort it is to actually see the changes made.

**Comment by NefariousTechSupport** [comment]
Sorry, got no idea why the whitespace is changing, the fc command on windows isn't showing it for me so uh yeah. I'll try and fix it but sorry

**Comment by Dinoguy1000** [comment]
Unfortunately that still didn't fix the diff Github generates. Instead of `fc`, copy the original file and your modified version into an online diff checker to spot where the other whitespace changes are.

**Comment by NefariousTechSupport** [comment]
I'm now pretty sure i fixed it, github desktop was changing my line endings for some reason
I also improved weights whilst i was at it

**Pull request closed without merging**
